### ISSUE TITLE
Now on Twitch require Authenticated API Requests

### ISSUE THREAD

**Issue by laizen** [KunaiFire/rechat-dl#3]
Since now Twitch require a Client ID to API Requests, and you script need this new feature to work. 
Look here to know more https://github.com/justintv/Twitch-API

If you can add this new feature like to use your script again. 
I cant do this because i not know almost nothing about Python XD
Nice work you have done until now.

**Comment by laizen** [comment]
Hi Again my friend help me with your code
First Get your Client ID -https://www.twitch.tv/kraken/oauth2/clients

Add This Line
`key_id = "?client_id=Client_ID_Here"`
And Edit This
`vod_info = requests.get("https://api.twitch.tv/kraken/videos/v" + sys.argv[1] + key_id).json()`

**Comment by makamys** [comment]
Are you sure you're using the latest version? I already handled this in commit 7011880, by using the client id read from a `client-id.txt` file in the directory of the script.

**Comment by makamys** [comment]
Made another update to this, with commit 1b37039, it should all work out of the box.
