### ISSUE TITLE
NewConnectionError while trying to download

### ISSUE THREAD

**Issue by tezJR** [KunaiFire/rechat-dl#5]
error while downloading chunk #1: HTTPConnectionPool(host='rechat.twitch.tv', po
rt=80): Max retries exceeded with url: /rechat-messages?start=1502496578&video_i
d=v166276411 (Caused by NewConnectionError('<requests.packages.urllib3.connectio
n.HTTPConnection object at 0x03588D50>: Failed to establish a new connection: [E
rrno 11004] getaddrinfo failed',))

Same error all tries on VODs from two different channels.

Is the issue on my end?

**Comment by TheSneakySniper** [comment]
No, it appears as if twitch has stopped using it's rechat API.

The program has completely broken now.
https://github.com/PetterKraabol/Twitch-Chat-Downloader/issues/23

Here is some reconnaissance I did on the issue. I hope someone fixes it.

**Comment by makamys** [comment]
Thanks for linking that issue, it was easy to update to the new API with the help of the comments in it. See commit 942f4b1.

By the way, I had no idea so many people were making tools for downloading rechat data! I guess my script isn't that useful now with better options around, but I'll keep it maintained while doing so is this simple.
